In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('House_pricing.csv')
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

## The .value_count method very usefull

In [11]:
df['FireplaceQu'].value_counts(dropna= False)

FireplaceQu
NaN    690
Gd     380
TA     313
Fa      33
Ex      24
Po      20
Name: count, dtype: int64

In [14]:
df['BsmtFinSF2'].value_counts(dropna=False,bins=6)

(-1.4749999999999999, 245.667]    1356
(245.667, 491.333]                  49
(491.333, 737.0]                    35
(737.0, 982.667]                    10
(982.667, 1228.333]                  9
(1228.333, 1474.0]                   1
Name: count, dtype: int64

- ### Doing the same work but using Groupby
- group by is usefull for applying aggrigate functions

In [52]:
df.groupby(['FireplaceQu'])['FireplaceQu'].count()

FireplaceQu
Ex     24
Fa     33
Gd    380
Po     20
TA    313
Name: FireplaceQu, dtype: int64

## Apply a custom function to a specific column of the dataset.

In [60]:
df['Functional_new'] = df['Functional'].apply((lambda  x : x.lower()))

### Apply string funtion on a column

In [15]:
df['FireplaceQu'] = df['FireplaceQu'].str.lower()
df['FireplaceQu']

0       NaN
1        ta
2        ta
3        gd
4        ta
       ...
1455     ta
1456     ta
1457     gd
1458    NaN
1459    NaN
Name: FireplaceQu, Length: 1460, dtype: str

## A series which has all values except the NaN values

In [68]:
df['FireplaceQu'][df['FireplaceQu'].notna()]

1       ta
2       ta
3       gd
4       ta
6       gd
        ..
1447    ta
1451    gd
1455    ta
1456    ta
1457    gd
Name: FireplaceQu, Length: 770, dtype: str

In [69]:
df['FireplaceQu'].notna()

0       False
1        True
2        True
3        True
4        True
        ...
1455     True
1456     True
1457     True
1458    False
1459    False
Name: FireplaceQu, Length: 1460, dtype: bool

### All the values which are NaN only

In [49]:
df['FireplaceQu'].isna().sum()
df['FireplaceQu'].count()

np.int64(690)

np.int64(770)

In [3]:
dup_subset = df[df.duplicated(subset=['Neighborhood', 'YearBuilt', 'LotArea'])]
dup_subset

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
156,157,20,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,109500
188,189,90,RL,64.0,7018,Pave,NaN,Reg,Bnk,AllPub,...,0,NaN,NaN,NaN,0,6,2009,WD,Alloca,153337
193,194,160,RM,24.0,2522,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,130000
199,200,20,RL,76.0,9591,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2009,WD,Normal,274900
223,224,20,RL,70.0,10500,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,3,2009,WD,Abnorml,97000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1422,1423,120,RM,37.0,4435,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,3,2008,WD,Normal,136500
1431,1432,120,RL,NaN,4928,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,143750
1441,1442,120,RM,NaN,4426,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,149300
1449,1450,180,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2006,WD,Abnorml,92000
1452,1453,180,RM,35.0,3675,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,145000